/// Cross-platform Noise KK test.
///
/// This test verifies that the Dart NoiseKK implementation produces
/// byte-identical output to the Node.js noise-protocol library.
///
/// Test vectors are generated by:
///   npx tsx packages/bridge/scripts/noise-test-vectors.ts
///
/// Since this is a Flutter test and we can't run it without the SDK,
/// the test structure is documented here for when Flutter is available.
///
/// To run:
///   cd packages/app
///   flutter test test/crypto/noise_kk_test.dart
library;

// import 'dart:convert';
// import 'dart:io';
// import 'dart:typed_data';
// import 'package:flutter_test/flutter_test.dart';
// import 'package:claude_remote/crypto/noise_kk.dart';
// import 'package:claude_remote/crypto/noise_session.dart';
//
// void main() {
//   late Map<String, dynamic> vectors;
//
//   setUpAll(() {
//     final file = File('test/crypto/noise_test_vectors.json');
//     vectors = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
//   });
//
//   group('Noise KK cross-platform compatibility', () {
//     test('prologue matches Node.js output', () async {
//       final psk = _hexDecode(vectors['psk'] as String);
//       final prologue = await NoiseKK.buildPrologue(psk);
//       expect(
//         _hexEncode(prologue),
//         equals(vectors['prologue'] as String),
//       );
//     });
//
//     // Note: Full handshake test requires deterministic ephemeral keys,
//     // which the current implementation generates randomly.
//     // To test byte-exact handshake, we'd need to either:
//     //   1. Inject ephemeral keys into NoiseKK (add a test-only constructor)
//     //   2. Or test at the transport level (encrypt/decrypt roundtrip)
//
//     test('transport encrypt/decrypt matches Node.js', () async {
//       // After a successful handshake with the bridge, verify that
//       // encrypting known plaintext produces known ciphertext.
//       // This validates:
//       //   - ChaCha20-Poly1305 IETF compatibility
//       //   - Nonce encoding (4 zero bytes + 8-byte LE counter)
//       //   - MAC computation
//       //
//       // NOTE: We can't test this without first completing a handshake,
//       // because the transport keys come from the handshake.
//       // Instead, we'd test this as an integration test.
//     });
//   });
// }
//
// Uint8List _hexDecode(String hex) {
//   final bytes = <int>[];
//   for (var i = 0; i < hex.length; i += 2) {
//     bytes.add(int.parse(hex.substring(i, i + 2), radix: 16));
//   }
//   return Uint8List.fromList(bytes);
// }
//
// String _hexEncode(Uint8List bytes) {
//   return bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join('');
// }
